---
- hosts: appservers
  become: true

  tasks:
  - name: Update and upgrade apt packages
    become: true
    apt:
      upgrade: yes
      update_cache: yes

  - name: install nginx
    apt: name=nginx state=present

  - name: install git
    apt: name=git state=present

  - name: Add Nodesource Keys
    become: yes
    apt_key:
      url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
      state: present

  - name: Add Nodesource Apt Sources
    become: yes
    apt_repository:
      repo: '{{ item }}'
      state: present
    with_items:
      - 'deb https://deb.nodesource.com/node_6.x xenial main'
      - 'deb-src https://deb.nodesource.com/node_6.x xenial main'

  - name: Install NodeJS
    become: yes
    apt:
      name: nodejs
      state: latest
      update_cache: yes

  - name: install pm2
    npm:
      name: pm2
      global: yes
